### ISSUE TITLE
Find an alternative to Google Fonts as the default font (privacy)

### ISSUE THREAD

**Issue by aral** [ThePacielloGroup/cupper#28]
Currently, the default template loads its fonts from Google Fonts, which is a service provided by Alphabet, Inc., a company that makes its money by tracking people and eroding their privacy for profit. Please consider using a privacy-friendly alternative hosted service or, even easier,  load the font locally from the static folder.

**Reference:** /themes/cupper/layout/_default/baseof.html:

```html
<link href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i,700" rel="stylesheet" media="none" onload="this.media='all';">
```

**Comment by Heydon** [comment]
@Aral. Cool — been meaning to do this for a while. Will do.

**Comment by Heydon** [comment]
Done. For an added perf gain, moved to just using Arial for the body font for now. The personality comes form Miriam Libre anyway.

**Comment by aral** [comment]
Thank you, Heydon, much appreciated :)
