### ISSUE TITLE
When two page titles have the same name, they are both highlighted when selected.

### ISSUE THREAD

**Issue by rikschennink** [ThePacielloGroup/cupper#31]
For instance

`frameworks/introduction.md`

`plugins/introduction.md`

When I select the introduction page under frameworks, the plugins one is highlighted as well.

**Comment by Heydon** [comment]
@rikschennink  Oh poo :-D Any ideas on how to fix welcome. I'll have a look later, otherwise.

**Comment by rikschennink** [comment]
@Heydon :-D I'll take a quick look, not the best at Hugo though.

**Comment by rikschennink** [comment]
@Heydon See pull request #32, resolves the issue in my FilePond docs.
