### ISSUE TITLE
Suggestion: consider renaming the product

### ISSUE THREAD

**Issue by colinbdclark** [ThePacielloGroup/cupper#8]
Hi @Heydon and other Paciello Group friends,

Your new Infusion documentation builder tool looks amazing, congratulations on releasing it! It is a much-needed tool for the web development community.

I was a bit surprised, though, to hear that you've chosen the name Infusion for it, given the overlap it has with [Infusion](https://fluidproject.org/infusion.html), the [open source accessible JavaScript framework](https://github.com/fluid-project/infusion) that has been developed by the [Fluid Project](https://fluidproject.org/) since 2008. Fluid Infusion is even something [you've written about on the Paciello Group blog](https://developer.paciellogroup.com/blog/2009/07/wai-aria-implementation-in-javascript-ui-libraries/) in the past.

I think a lot of potential users might really benefit from using both of our tools, but if they have the same name, users might be confused about which one is which or be unable to distinguish between them.

The accessibility community has always been a small and supportive one. With this in mind, I hope you might consider a new name for your documentation builder platform, in order to continue to support the work that the Fluid Project has been doing for over a decade now in helping to "infuse" accessibility and personalization into the web development workflow with our Infusion framework.

Best regards,

Colin

**Comment by Heydon** [comment]
@colinbdclark Hi! Just to acknowledge your issue and say we're scheduling a quick meeting to discuss this internally. I regret I was not personally aware of your product or the Paciello Group blog post.

**Comment by colinbdclark** [comment]
Hi @Heydon, any updates on this?

**Comment by Heydon** [comment]
Hi @colinbdclark,
I was not working with The Paciello Group when the post about Fluid Infusion was written some 8 years ago and was not aware of it, I'm afraid. 

It is indeed regrettable that the two projects use the term "Infusion" (as do a number of projects, companies, and products). I guess this is why people turned to using non-dictionary words, or taking dictionary words and removing vowels during the Web 2.0 period.

Given the clear differences in purpose, scope, branding and technologies, I don't feel there is any need to change the name of our documentation builder and, indeed, a renaming and rebranding exercise at this point would be costly.

However, as a matter of professional curtesy, perhaps it would be a good idea to place a disambiguation note in our repository's `README.md` pointing to your framework?

**Comment by colinbdclark** [comment]
Hi @Heydon. Thanks for your response, I appreciate it. I do hope you'll reconsider. The accessibility community has always been such a small and supportive one, and the stakes are so high for the work we are mutually doing. The more we can help each other out, the stronger our effect will be.

In terms of the name, I totally understand how accidental overlap happens. Naming is really hard. When I start a new project on Github (and I have a number of open source projects where I had to agonize over the name), I usually do quite a lot of searching to find out if there are other projects that I might be overlapping with. 

First, I search for repositories on Github and spend a bit of time reading about what they do. Fluid's Infusion was and still is the likely first hit you'll get when you search for "infusion" here, and the connection with accessibility and inclusive design is apparent.

I also look on prominent package management systems, especially ones that I will am using in the project itself. For example, the npm registry. There, too, you will find that the <code>infusion</code> package name (which your Infusion is incorrectly using) is already in use by the Fluid community, and that regular releases to the package occur.

I often do a bit of Googling, too, using keywords that are relevant to what my project does. "Infusion inclusive design" or "infusion accessibility" or even "infusion accessible documentation" likely would have quickly turned up references to our community and project.

The Fluid community has been actively using the name Infusion for our inclusive design framework since 2008. Our Infusion has been regularly released, used, improved, and contributed to since then, and it continues to be a vibrant open source project. We're a friendly, committed community with years of experience helping to make the web more accessible. We've always thought of The Paciello Group as friends and valued colleagues, and many of us have worked on accessibility projects with your co-workers.

Again, I hope you'll reconsider your position and explore new names for this project.

**Comment by waharnum** [comment]
Greetings - @Heydon - as both a developer on / with the Infusion framework and a fan of the Hugo static generator your Infusion documentation generator is built on, I have to echo @colinbdclark's hope that you'll reconsider this naming. 

This looks like a great project, but it's an unfortunate collision in the open source accessible software namespace to have two accessible / inclusive design projects with the same name, and I worry about both confusion in the wider community and more practical issues around package management and distribution.

**Comment by jobara** [comment]
@Heydon to further @waharnum and @colinbdclark remarks, it's worthwhile to note that the Infusion Framework has a [documentation site](https://docs.fluidproject.org/infusion/development/). That means that anyone searching for "Infusion Documentation" will now have to disambiguate docs meant for the Infusion Framework and your tool.

**Comment by avtar** [comment]
> Given the clear differences in purpose, scope, branding and technologies, I don't feel there is any need to change the name of our documentation builder

One could argue that the scope of both projects is to promote accessibility and inclusive design. While there are [some other projects that share the same name](https://github.com/search?utf8=%E2%9C%93&q=infusion&type=) none of them seem to directly share that scope as Fluid Project's Infusion and now Paciello Group's. The points raised in this thread about npm naming conflicts and conflated search results would warrant more reflection :)

**Comment by amb26** [comment]
Hi there @Heydon - just wanted to add my voice to the hopes that you will graciously reconsider the naming. I think there is a real risk of confusion and ambiguity and think it would be a real service to the a11y community to head it off - not least if we considered using your docs platform for our own documentation, which we might well do given how well-engineered it looks, and had to explain to our users that we had the "Infusion documentation written in Infusion" : P As others note, ours https://github.com/fluid-project/infusion is a very long-lived and active project with thousands of commits and dozens of contributors serving the accessibility community, and in addition has been published with that artifact name in npm for several years. It would be indeed very gracious if you would devote the time to thinking of another name, and we dearly hope you would.
All the best,
Antranig

**Comment by SteveALee** [comment]
On ballance I have to say that we, as the accessibility / inclusive design community would better serve everyone if we avoid this unfortunate name clash. A few observations:

*  While the 2 projects do have a different scope, which might be OK for tradmarks, the fact they are both inclusivity oriented software projects found primarily on the web makes the name clash a problem. People will be come confused when searching for either.
* I realise a name change will involve conciderable effort for either project but I think it will be less onerous for this one. Plus the IDRC project is older and more mature. The 'brand' is thus reasonably well established.
* IDRC Infusion is the technology behind key parts of the large GPII vision and so can be expected to have a higer visibility and wide useage.
* Both projects chose 'infusion' to describe an important aspect but perhaps we can find a new one for this project, while keeping the cup logo? How about Tisane  or perhaps Matcha?
* I'm willing to help with the mechanics of a rename, given this project is open source.

I do hope we can resolve this. I concider both projects to be excellent in different ways.

**Comment by Heydon** [comment]
@colinbdclark et al,

Well, word travels round fast, eh? 😉

Just to say we are actively looking into a new brand/name now. May take a little while. I will need your help to get the word out when we switch, though! Deal?

**Comment by SteveALee** [comment]
Of course. Plus i'll put on the recently launched GPII Developer Space for extra exposure (hopefully) ds.gpii.net

**Comment by avtar** [comment]
@Heydon That's great to hear! Thank you 🤝

**Comment by colinbdclark** [comment]
That's wonderful news, thank you very much @Heydon. Let us know how we can help ensure the word travels round fast for your new name and brand. ;) We really appreciate it, and the extra inconvenience you've had to go through for this.

**Comment by Heydon** [comment]
@colinbdclark Introducing, **Cupper**!

**Comment by SteveALee** [comment]
Great name - made me think of this - https://www.youtube.com/watch?v=HgzEBLa3PPk
