### ISSUE TITLE
Headings in demo code are included in TOC

### ISSUE THREAD

**Issue by IanPouncey** [ThePacielloGroup/cupper#9]
The following code will add "Some heading" to the generated table of contents:

```
{{demo}}
<h2>Some heading</h2>
{{/demo}}
```

Headings, specifically `h2` elements, in demo content should not be part of the TOC.

This raises a question about how to write good demonstration code, as any use of headings in a demo will be parsed in the same way as any other headings on the page and should, therefore, be appropriately nested. This can, I think, be handled by advice on the "Writing inline demos" page.

**Comment by Heydon** [comment]
Thanks @IanPouncey. Removing the `<h2>`s from the tables of content will mean adjusting the Go template logic in the [toc partial](https://github.com/ThePacielloGroup/infusion/blob/master/themes/infusion/layouts/partials/toc.html).

## Template contents

```
{{ $headings := findRE "<h2.*?>(.|\n])+?</h2>" .Content }}
{{ if ge (len $headings) 2 }}
  <nav class="toc" aria-labelledby="toc-heading">
    <h2 id="toc-heading">Table of contents</h2>
    <ol>
      {{ range $headings }}
        <li>
          <a href="#{{ . | htmlUnescape | plainify | urlize }}">
            {{ . | htmlUnescape | plainify }}
          </a>
        </li>
      {{ end }}
    </ol>
  </nav>
{{ end }}
```

Yay! We need to rewrite the regex to parse the HTML better. Or (last resort) remove the heading with JS after the fact...
